# Generated by Django 4.2.7 on 2024-03-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyst2024app', '0002_account_video_question_video_time_video_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.CharField(default='no_username', max_length=100),
        ),
    ]
