# Generated by Django 4.2.7 on 2024-03-23 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyst2024app', '0003_account_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('question', models.CharField(max_length=255)),
                ('time', models.IntegerField(max_length=100)),
            ],
        ),
    ]
