# Generated by Django 4.2.7 on 2024-03-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skyst2024app', '0005_alter_videoinfo_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoinfo',
            name='question',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
