name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Pull Repo
      run: |
        pwd
        git pull
        sudo lsof -t -i tcp:8000 | xargs kill -9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        python manage.py makemigrations	
        python manage.py migrate
        nohup gunicorn --bind 0.0.0.0:8000 skyst2024.wsgi > nohup.out 2> nohup.err < /dev/null
